### ISSUE TITLE
Multiple Tag components?

### ISSUE THREAD

**Issue by 1-800-jono** [JFusco/react-tagging-input#2]
Is it possible to have multiple `<Tags />` components as siblings?

I currently get an errors trying to achieve this.

Thanks!

**Comment by JFusco** [comment]
Hi @jonathanphz !
Thanks for checking this out - yes, it's possible to have multiple Tags on a page, the example page has multiple - https://jfusco.github.io/react-tagging-input/

Can you review the example? If you are still get an error, can you paste it here?

**Comment by JFusco** [comment]
@jonathanphz 
As siblings, as in, you want to put a Tag component inside of a Tag component? May I ask the use case for this?

**Comment by 1-800-jono** [comment]
Well I have a form that will need two Tags components with different data. I tried changing `tags={this.state.tags}` of the second Tag component to `tags={this.state.optionalTags}` but got some errors. Will need to double check what was the error again

Example:

`<Tags
    tags={this.state.optionalTags}
   } />`

**Comment by JFusco** [comment]
@jonathanphz 
Looks like you have an extra "}" at the end of your element, can you remove that and try again? It should be 

`<Tags tags={this.state.optionalTags} />`

Can you try to post a working example so I can try to reproduce on my end? I just tried and it's working as expected, here's the code:

```
class App extends Component {
  state = {
    tagsOne: ['hello', 'world'],
    tagsTwo: ['foo', 'bar']
  };

  render(){
    <div>
        <Tags tags={this.state.tagsOne} />
        <Tags tags={this.state.tagsTwo} />
    </div>
  }
}
```

**Comment by 1-800-jono** [comment]
Yes this is working - I probably did something stupid before and that's why it wasn't working. Thanks for the help man - going to close the issue.

**Comment by JFusco** [comment]
@jonathanphz 
You're welcome, thanks for confirming and closing
